In [109]:
import numpy as no
import pandas as pd

In [110]:
df = pd.read_csv('encoding.csv')

In [111]:
df.sample(10)

     Age  Gender     Review Education Purchased
197   21    Male  Excellent    School       Yes
46    24    Male  Excellent    School       Yes
10    41  Female    Average    School        No
39    42  Female    Average    School        No
13    41    Male  Excellent    School       Yes
118   18  Female       Poor        UG        No
172   32  Female    Average    School        No
148   23  Female    Average        UG        No
176   58    Male    Average    School        No
161   58  Female    Average    School        No

In [112]:
df = df.iloc[:,2:]

In [113]:
df

        Review Education Purchased
0    Excellent        UG       Yes
1      Average        PG       Yes
2    Excellent    School       Yes
3         Good    School        No
4      Average    School        No
..         ...       ...       ...
195  Excellent        PG       Yes
196  Excellent        PG       Yes
197  Excellent    School       Yes
198       Good        PG       Yes
199  Excellent        UG       Yes

[200 rows x 3 columns]

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
X_train,X_test,y_train,y_test = train_test_split((df.iloc[ : ,0:2]),(df.iloc[ : , 2:]),test_size=0.2)

In [116]:
y_test.shape

(40, 1)

In [117]:
X_train

        Review Education
130  Excellent    School
13   Excellent    School
117    Average    School
95     Average        UG
198       Good        PG
..         ...       ...
97        Good        PG
191  Excellent    School
11     Average        UG
44        Good        UG
180    Average    School

[160 rows x 2 columns]

In [118]:
from sklearn.preprocessing import OrdinalEncoder

In [119]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good','Excellent'],['School','UG','PG']])

In [120]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good', 'Excellent'],
                           ['School', 'UG', 'PG']])

In [121]:
X_train_encoded= oe.transform(X_train)

In [122]:
X_test_encoded = oe.transform(X_test)

In [123]:
X_train_encoded = pd.DataFrame(X_train_encoded,columns=X_train.columns,dtype='int')

In [124]:
X_test_encoded = pd.DataFrame(X_test_encoded,columns=X_test.columns)

In [125]:
X_train_encoded

     Review  Education
0         3          0
1         3          0
2         1          0
3         1          1
4         2          2
..      ...        ...
155       2          2
156       3          0
157       1          1
158       2          1
159       1          0

[160 rows x 2 columns]

In [126]:
oe.categories_

[array(['Poor', 'Average', 'Good', 'Excellent'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [127]:
from sklearn.preprocessing import LabelEncoder

In [128]:
le = LabelEncoder()

In [129]:
le.fit(y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LabelEncoder()

In [130]:
y_train_scaled = le.transform(y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [131]:
y_test_scaled = le.transform(y_test)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [132]:
y_train_scaled = pd.DataFrame(y_train_scaled)

In [133]:
y_train_scaled

     0
0    1
1    1
2    0
3    0
4    1
..  ..
155  1
156  1
157  0
158  1
159  0

[160 rows x 1 columns]