In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
car = pd.read_csv('cars.csv')

In [5]:
car.sample(5)

       brand  km_driven    fuel         owner  selling_price
1078   Lexus      20000  Petrol   First Owner        5150000
698   Maruti      40000  Diesel   First Owner         680000
5251  Toyota      79328  Diesel  Second Owner         750000
7636  Maruti      36000  Petrol  Second Owner         250000
5514   Skoda      31000  Diesel   First Owner         860000

In [12]:
car['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [17]:
car['brand'].nunique()

32

In [21]:
car['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [22]:
car['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# Using pandas

In [23]:
pd.get_dummies(car,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [26]:
pd.get_dummies(car,columns=['fuel','owner'],dtype='int')   #for 0 and one not true false

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

# 2) k-1 One-hot encoding deleting first column

In [32]:
pd.get_dummies(car,columns=['fuel','owner'],drop_first=True)   # Delete first column of new columns

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [38]:
car

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [50]:
# using SKlearn

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
X_train,X_test,y_train,y_test = train_test_split(car[['brand','km_driven','fuel','owner']],car['selling_price'],test_size=0.2,random_state=0)

In [53]:
X_train

           brand  km_driven    fuel         owner
3042     Hyundai      60000     LPG   First Owner
1520        Tata     150000  Diesel   Third Owner
2611     Hyundai     110000  Diesel  Second Owner
3544    Mahindra      28000  Diesel  Second Owner
4138      Maruti      15000  Petrol   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[6502 rows x 4 columns]

In [54]:
y_train

3042     375000
1520     150000
2611     459999
3544    1050000
4138     700000
         ...
4931     300000
3264     220000
1653     170000
2607     375000
2732     225000
Name: selling_price, Length: 6502, dtype: int64

In [75]:
from sklearn.preprocessing import OneHotEncoder

In [76]:
ohe = OneHotEncoder(drop='first',dtype='int',sparse_output=False)

In [77]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [78]:
X_test_new=ohe.transform(X_test[['fuel','owner']])

In [79]:
X_train_encoded=np.hstack((X_train[['brand','km_driven']].values,X_train_new))

In [80]:
X_test_encoded=np.hstack((X_test[['brand','km_driven']],X_test_new))

In [83]:
X_test_encoded

array([['Hyundai', 40000, 1, ..., 0, 0, 0],
       ['Mahindra', 70000, 1, ..., 0, 0, 0],
       ['Maruti', 5000, 0, ..., 0, 0, 0],
       ...,
       ['Maruti', 40000, 1, ..., 0, 0, 0],
       ['Hyundai', 2350, 0, ..., 0, 0, 0],
       ['Hyundai', 80000, 1, ..., 1, 0, 0]], shape=(1626, 9), dtype=object)

In [ ]:
# OHE with only top categories

In [90]:
counts = car['brand'].value_counts()

In [95]:
car['brand'].nunique()
threshold = 100

In [96]:
repl = counts[counts <= threshold].index

In [99]:
(pd.get_dummies(car['brand'].replace(repl, 'other'),dtype=np.int32).sample(5))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,other
3624,0,0,0,0,1,0,0,0,0,0,0,0,0
3101,0,0,0,0,0,0,1,0,0,0,0,0,0
7245,0,0,0,0,1,0,0,0,0,0,0,0,0
1771,0,0,0,0,1,0,0,0,0,0,0,0,0
2698,0,0,0,0,0,1,0,0,0,0,0,0,0